name: Qodana
on:
  workflow_call:
    inputs:
      upload-result:
        description: Upload Qodana scan result
        required: false
        default: true
        type: boolean

    secrets:
      QODANA_TOKEN:
        required: false

concurrency:
  group: '${{ github.workflow }}-${{ github.event.number || github.ref }}'
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2022.3.4
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

        with:
          cache-default-branch-only: true
          upload-result: ${{ inputs.upload-result }}

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
