name: Gradle build
on:
  workflow_call:
    inputs:
      jdk-version:
        description: JDK version to use
        required: false
        type: string
        default: "17"

      gradle-version:
        description: Gradle version to use
        required: false
        type: string

      gradle-build-args:
        description: Gradle build args
        required: false
        type: string
        default: build

      gradle-build-scan:
        description: Enable Gradle publish Gradle Build Scan
        required: false
        type: boolean
        default: false

      reports-path:
        description: Path to build reports to upload
        required: false
        type: string
        default: ""

      artifacts-path:
        description: Path to build artifacts to upload
        required: false
        type: string
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ inputs.jdk-version }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ inputs.gradle-version }}
          validate-wrappers: true
          gradle-home-cache-cleanup: true
          add-job-summary-as-pr-comment: on-failure
          build-scan-publish: ${{ inputs.gradle-build-scan }}
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        id: build
        run: ./gradlew ${{ inputs.gradle-build-args }}

      - name: Upload build reports
        uses: actions/upload-artifact@v4
        if: ${{ inputs.reports-path != '' }}
        with:
          name: build-reports
          path: ${{ inputs.reports-path }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: ${{ inputs.artifacts-path != '' }}
        with:
          name: build-artifacts
          path: ${{ inputs.artifacts-path }}
