name: Release
on:
  workflow_call:
    outputs:
      release-created:
        description: Whether a release was created
        value: ${{ steps.release.outputs.release-created }}

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release.outputs.release-created }}

    steps:
      - name: Release Please Action
        id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json
